"""Declarative base for all BreachAlert ORM models.

This module defines the single shared `Base` class that every SQLAlchemy
model in the project must inherit from. Keeping it isolated here avoids
circular imports: models import `Base` from this module, and Alembic /
session setup import the models.

Usage in a model module:

    from app.db.base import Base

    class User(Base):
        __tablename__ = "users"
        id: Mapped[str] = mapped_column(primary_key=True)
"""

from __future__ import annotations

import re
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Consistent constraint naming convention. This is important for Alembic so
# that autogenerated migrations produce stable, predictable constraint names
# (especially for unnamed indexes, unique constraints, and foreign keys).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models.

    All models inherit from this class so that they share a single
    `MetaData` registry. Alembic uses `Base.metadata` as its
    `target_metadata` for autogeneration.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    @declared_attr.directive
    def __tablename__(cls) -> str:
        """Derive a default snake_case table name from the class name.

        Example: `BreachFinding` -> `breach_finding`. Models may still
        override this by explicitly declaring their own `__tablename__`.
        """
        name = re.sub(r"(?<!^)(?=[A-Z])", "_", cls.__name__).lower()
        return name


class TimestampMixin:
    """Reusable mixin adding created/updated timestamp columns.

    Optional: models can inherit from this in addition to `Base` to gain
    automatic `created_at` and `updated_at` tracking.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )